### ISSUE TITLE
Where to add extra user/item features?

### ISSUE THREAD

**Issue by jasperhyp** [BUPT-GAMMA/Design-Space-for-GNN-based-CF#2]
Hello,  Thanks for sharing the code!  I was wondering if there's any built-in space where I can add extra flat features of users (say, years of usage, age, sex, etc.) and items (e.g. reputation, source location, etc.).  Is it a common practice to just concatenate the features to the initial embedding and update together during training?  Or is it better to concatenate that when decoding and use another decoder, e.g. a bilinear one or an MLP+concat?  It also looks like some of the papers you cited do not support adding plain features by itself (e.g. LightGCN, LR-GCCF).

Thanks!

**Comment by AliciaaaWang** [comment]
Hi, sorry for the late reply. If you want to add extra features, you can refer to the default feature encoders or customize your own encoders in [feature_encoder.py](https://github.com/BUPT-GAMMA/Design-Space-for-GNN-based-CF/blob/main/graphgym/models/feature_encoder.py). And the encoded features can serve as the initial embeddings which will be input to the model architecture.

> Hello, Thanks for sharing the code! I was wondering if there's any built-in space where I can add extra flat features of users (say, years of usage, age, sex, etc.) and items (e.g. reputation, source location, etc.). Is it a common practice to just concatenate the features to the initial embedding and update together during training? Or is it better to concatenate that when decoding and use another decoder, e.g. a bilinear one or an MLP+concat? It also looks like some of the papers you cited do not support adding plain features by itself (e.g. LightGCN, LR-GCCF).
> 
> Thanks!
